# https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path
# https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-Apache-Maven

name: Maven Package

on:
  push:
#  release:
#    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
        cache: 'maven'
        # server-id: 'github' # Value of the distributionManagement/repository/id field of the pom.xml # default: 'github'
        # settings-path: ${{ github.workspace }} # location for the settings.xml file # default: $HOME/.m2

    - name: Build with Maven
      run: mvn -B --file pom.xml clean install

    - name: Publish to GitHub Packages Apache Maven
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        REPO="github::https://maven.pkg.github.com/${GITHUB_REPOSITORY}"
        mvn -Dmaven.test.skip -DaltDeploymentRepository="${REPO}" -DaltReleaseDeploymentRepository="${REPO}" -DaltSnapshotDeploymentRepository="${REPO}" -Penunciate-full-tests -B deploy
