# https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path
# https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-Apache-Maven

name: Maven Package

on:
  push:
#  release:
#    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
        cache: 'maven'
        # server-id: 'github' # Value of the distributionManagement/repository/id field of the pom.xml # default: 'github'
        # settings-path: ${{ github.workspace }} # location for the settings.xml file # default: $HOME/.m2

    - name: Build with Maven
      run: mvn -B --file pom.xml clean install

    - name: Publish to GitHub Packages Apache Maven
      env:
        GITHUB_TOKEN: ${{ github.token }}        
      run: |
        REPO="github::https://maven.pkg.github.com/${GITHUB_REPOSITORY}"
        mvn -Dmaven.test.skip -DaltDeploymentRepository="${REPO}" -DaltReleaseDeploymentRepository="${REPO}" -DaltSnapshotDeploymentRepository="${REPO}" -Penunciate-full-tests -B deploy

    - name: Set up xIT maven repo
      uses: actions/setup-java@v2
      with: # running setup-java again overwrites the settings.xml
        java-version: '16'
        distribution: 'adopt'
        cache: 'maven'
        server-id: xit-public-releases # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: MAVEN_USERNAME # env variable for username in deploy
        server-password: MAVEN_PASSWORD # env variable for token in deploy

    - name: Publish to xIT maven repo
      env:
        MAVEN_USERNAME: 'deployer.public'
        MAVEN_PASSWORD: ${{ secrets.XIT_MAVEN_PUBLIC_REPO_PASSWORD }}
      run: |
        REPO="xit-public-releases::https://repository.xit.camp/repository/maven-public-snapshots"
        mvn -Dmaven.test.skip -DaltDeploymentRepository="${REPO}" -DaltReleaseDeploymentRepository="${REPO}" -DaltSnapshotDeploymentRepository="${REPO}" -Penunciate-full-tests -B deploy

      
